name: Stop Review
on:
  pull_request:
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'Branch where review environment was created from (as in GitHub)'     
        required: true
      pr_number:
        description: "Pull request number of the environment creator"

env:
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW }}

jobs:
  stop_review:
    runs-on: ubuntu-latest
    name: Stop Review
    steps:
      - uses:  Hi-Fi/kolga-setup-action@feat/input_possibility
        with:
          head_ref: ${{ github.event.inputs.head_ref }}
          pr_number: ${{ github.event.inputs.pr_number }}
      - run: echo "hello"
